Document: graspit
Title: Debian graspit Manual
Author: <insert document author here>
Abstract: This manual describes what graspit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/graspit/graspit.sgml.gz

Format: postscript
Files: /usr/share/doc/graspit/graspit.ps.gz

Format: text
Files: /usr/share/doc/graspit/graspit.text.gz

Format: HTML
Index: /usr/share/doc/graspit/html/index.html
Files: /usr/share/doc/graspit/html/*.html
